services:
  server:
    image: ru.ipal-otel-demo-server:latest
    ports:
      - "8080:8080"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_LOGS_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_TRACES_EXPORTER: otlp
      # JAVA_TOOL_OPTIONS: "-Dotel.java.global-autoconfigure.enabled=true"
    # healthcheck:
    #   test: [ "CMD", "wget", "-qO", "-", "localhost:8080/actuator/health" ]
    #   start_period: 4s

  client:
    image: ru.ipal-otel-demo-client:latest
    ports:
      - "8081:8081"
    environment:
      SERVER_ADDR: "server:8080"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_LOGS_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_TRACES_EXPORTER: otlp
      # JAVA_TOOL_OPTIONS: "-Dotel.java.global-autoconfigure.enabled=true"
    # depends_on:
    #   server:
    #     # condition: service_healthy
    #     condition: service_started

  collector:
    image: otel/opentelemetry-collector-contrib:0.132.2
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      # - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics  (http://localhost:8889/metrics)
      # - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.9.0
    ports:
      - "16686:16686" #UI
      # - "4317:4317" #OTLP gRPC
      # - "4318:4318" #OTLP http

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to increase heap size
      # - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411

  prometheus:
    image: prom/prometheus:v3.5.0
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000 #admin/grafana in web ui
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage: {}
