{
 "title": "Dashboard (Micrometer instrumentation)",
 "description": "has different metrics names!",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "http_route",
    "query": {
     "query": "label_values(http_server_requests_milliseconds_sum,uri)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(http_server_requests_milliseconds_sum,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "New panel",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "target_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Compilation time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(jvm_compilation_time_milliseconds_total[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Thread states",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "jvm_threads_states{job=\"$job\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "GC Overhead (CPU % spent for GC)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "sum by (job) (jvm_gc_overhead)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM GC Pause Duration 95% And Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, job) (rate(jvm_gc_pause_milliseconds_bucket[5m])))",
     "legendFormat": "50% {{job}}"
    }
   ]
  },
  {
   "title": "JVM memory usage (used vs committed)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job) (jvm_memory_committed_bytes{job=\"$job\",area=\"heap\"})",
     "legendFormat": "committed {{job}} {{jvm_memory_type}}"
    },
    {
     "expr": "sum by(job)(jvm_memory_used_bytes{job=\"$job\",area=\"heap\"})",
     "legendFormat": "used {{job}} {{jvm_memory_type}}"
    },
    {
     "expr": "max by(job) (jvm_memory_max_bytes{job=\"$job\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Committed heap breakdown",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{job=\"$job\"}",
     "legendFormat": "{{area}} -- {{id}}"
    }
   ]
  },
  {
   "title": "Used heap breakdown",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{area}} -- {{id}}" }
   ]
  },
  { "title": "Server request performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Server throughput (rps)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job, uri, status) (irate(http_server_requests_milliseconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server latency via summary",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_milliseconds",
     "legendFormat": "{{job}} -- {{method}} -- {{status}} -- {{uri}} -- {{quantile}}"
    }
   ]
  },
  {
   "title": "HTTP Client latencies",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "http_client_requests_milliseconds",
     "legendFormat": "{{job}} -- {{method}} -- {{outcome}} -- {{quantile}} -- {{status}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(job) (process_cpu_usage*system_cpu_count)",
     "legendFormat": "via recent jvm usage  gauge - {{job}}"
    },
    {
     "expr": "sum by(job) (rate(process_cpu_time_nanoseconds_total[5m]) *1E-9)",
     "legendFormat": "via cpu time counter - {{job}}"
    }
   ]
  }
 ]
}