receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  debug:
    verbosity: basic
  debug/1:
    verbosity: detailed
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
  prometheus:
    endpoint: 0.0.0.0:8889
#    namespace: default #adds this prefix to every metric


service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, zipkin, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite,prometheus, debug/1]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
